# Model Configuration
model_name: "all-MiniLM-L6-v2"

# Vector DB (Qdrant)
qdrant:
  storage_path: "./qdrant_storage"
  collection: "demo_code_collection"

# Data Processing
splitter:
  chunk_size: 1000
  chunk_overlap: 100