# Model Configuration
model_name: "all-MiniLM-L6-v2"
finetuned_model_path: "finetuned_model"

# Vector DB (Qdrant)
qdrant:
  storage_path: "./qdrant_storage"
  demo_collection: "demo_code_collection"
  eval_base_collection: "cosqa_base"
  eval_finetuned_collection: "cosqa_finetuned"

# Data Processing
splitter:
  chunk_size: 1000
  chunk_overlap: 100

# Fine-tuning
training:
  batch_size: 16
  num_epochs: 1
  # max_train_steps: 500
  max_train_steps: 50