# Model Configuration
model_name: "all-MiniLM-L6-v2"

# Vector DB (Qdrant)
qdrant:
  storage_path: "./qdrant_storage"
  demo_collection: "demo_code_collection"
  eval_base_collection: "cosqa_base"

# Data Processing
splitter:
  chunk_size: 1000
  chunk_overlap: 100